#server.port=7777
#
#zuul.routes.api-a.path=/api-a/**
#zuul.routes.api-a.serviceId=feign-consumer
#
#zuul.routes.api-b.path=/api-b/**
#zuul.routes.api-b.serviceId=feign-consumer
#
#eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/,http://localhost:1112/eureka/
#security.oauth2.resource.token-info-uri=http://localhost:9876/oauth/check_token
#security.oauth2.client.client-id=clientId
#security.oauth2.client.client-secret=secretId
#security.oauth2.client.user-authorization-uri=http://localhost:9876/oauth/authorize
#security.oauth2.client.access-token-uri=http://localhost:9876/oauth/token
#security.oauth2.client.grant-type=client_credentials

