#spring.application.name=composite-service
#server.port=3001
#spring.rabbitmq.host=localhost
#spring.sleuth.sampler.percentage=1.0
#spring.sleuth.hystrix.strategy.enabled=true
#spring.sleuth.stream.enabled=true
#spring.zipkin.baseUrl=http://localhost:9967
#spring.zipkin.enabled=true
#sample.zipkin.emabled=true
#eureka.client.serviceUrl.defaultZone=

spring:
  application:
    name: composite-service
server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:1111/eureka/,http://eureka-secondary:1112/eureka/,http://eureka-tertiary:1113/eureka/